version: "3.7"

services:
  server:
    image: sunfounder/pironman5:mini-1.3.11@sha256:138837ea0e979ea17105b6156398407e5844e3421dc18d6a61faa40111216810
    restart: on-failure
    network_mode: host
    pid: host
    privileged: true
    environment:
      CONFIG_PATH: /data/config.json
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - /dev:/dev
      - /lib/modules:/lib/modules:ro
      - /:/host:ro
      - /proc:/proc:ro
      - /sys:/sys:ro
