version: "3.7"

services:
  server:
    image: sunfounder/pironman5:pro-max-1.3.10@sha256:23dc94c695f85b792a65f0ed0c17993b20cfcc1ca77fddd449a565eeda9c173a
    restart: on-failure
    network_mode: host
    pid: host
    privileged: true
    environment:
      CONFIG_PATH: /data/config.json
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - /dev:/dev
      - /lib/modules:/lib/modules:ro
      - /:/host:ro
      - /proc:/proc:ro
      - /sys:/sys:ro
